// autogenerated java class stub
package cz.upol.vanusanik.disindent.runtime.natives;

import cz.upol.vanusanik.disindent.runtime.types.Method;
import cz.upol.vanusanik.disindent.runtime.types.DList;

public class System {
	
    public static Object apply(Method f, DList<Object> arguments) throws Exception{
    	Object[] args = arguments.toObjectArray();
    	
    	Class<?>[] classes = new Class<?>[args.length];
    	for (int i=0; i<args.length; i++)
    		classes[i] = args[i] == null ? null : args[i].getClass();
    	return f.getMethod(classes).invoke(null, args);
    }

}
