// autogenerated java class stub
package cz.upol.vanusanik.disindent.runtime.natives;

import cz.upol.vanusanik.disindent.runtime.types.Method;
import cz.upol.vanusanik.disindent.runtime.types.DList;

public class System {
	
    public static Object apply(Method f, DList<Object> arguments) throws Throwable {
    	Object[] args = arguments.toObjectArray();
    	return f.invoke(args);
    }
    
    public static Object distributed(Method f, DList<Object> arguments) throws Throwable {
    	Object[] args = arguments.toObjectArray();
    	return null;
    }

}
